on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements-lint.txt
    - name: Lint
      run: make lint
