name: tests

on:
  pull_request:

env:
  python-version: "3.10"

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run safety
        run: |
          safety check
      - name: Run bandit
        run: |
          bandit --ini .bandit

  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run isort
        run: |
          isort --check-only .
      - name: Run black
        run: |
          black . --check

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Test
        run: |
          pytest --cov
